# Generated by Django 5.1.1 on 2025-04-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0025_finalize_district_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='original_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='video_app.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observer',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='video_app.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='module',
            field=models.CharField(choices=[('4', 'Module 4: Think Like a Data Scientist'), ('2', 'Module 2: Classroom Census')], default='4', max_length=20),
        ),
    ]
