# Generated by Django 5.1.1 on 2025-04-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0026_session_archived_at_session_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadmin',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='video_app.district'),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customadmin',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
